#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J particle-serial
#SBATCH -o particle-serial.stdout
#SBATCH -n 1         
#SBATCH -p gpu
#SBATCH -t 00:10:00     
./serial -n 2000 -o serial.txt
./autocorrect -s serial.txt
