#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J particle-gpu
#SBATCH -o particle-gpu.stdout
#SBATCH -n 1         
#SBATCH -p gpu
#SBATCH -t 00:10:00     
ibrun ./gpu -n 2000 -o gpu.txt
./autocorrect -s gpu.txt
